---
- name: Update apt packages
  apt: upgrade=yes update_cache=yes
  when: ansible_facts['os_family'] == "Debian"
- name: Ensure basic system packages are installed
  apt:
    pkg:
      - python3-pip
      - python3-apt
      - build-essential
      - jq
      - curl
      - wget
      - zsh
      - git
    state: present
- name: Update yum packages
  yum: name=* state=latest
  when: ansible_facts['os_family'] == "RedHat"
- name: Install development tools
  yum:
    name: "@Development tools"
    state: present
  when: ansible_facts['os_family'] == "RedHat"
