---
- name: Add RPM GPG key for RPM based systems
  rpm_key:
    state: present
    key: https://repo.logdna.com/logdna.gpg
  when: ansible_facts['os_family'] == "RedHat"
- name: Add LogDNA repo to RPM Based systems
  blockinfile:
    path: /etc/yum.repos.d/logdna.repo
    block: |
      [logdna]
      name=LogDNA packages
      baseurl=https://repo.logdna.com/el6/
      enabled=1
      gpgcheck=1
      gpgkey=https://repo.logdna.com/logdna.gpg1
  when: ansible_facts['os_family'] == "RedHat"
- name: Install LogDNA agent on RPM based systems
  yum:
    name: logdna-agent
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  ignore_errors: "{{ ansible_check_mode }}"
- name: Add logdna apt-key to Deb based systems
  apt_key:
    url: https://repo.logdna.com/logdna.gpg
    state: present
  when: ansible_facts['os_family'] == "Debian"
- name: Add logdna repo to Deb based systems
  apt_repository:
    repo: deb https://repo.logdna.com stable main
  when: ansible_facts['os_family'] == "Debian"
- name: Update apt packages on Deb based systems
  apt: update_cache=yes
  when: ansible_facts['os_family'] == "Debian"
- name: Install logdna-agent on Deb based systems
  apt:
    name: logdna-agent
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"
  ignore_errors: "{{ ansible_check_mode }}"
- name: set logdna-agent ingestion key 
  shell: logdna-agent -k "{{ logdna_ingestion_key }}"
- name: set logdna-agent api endpoint 
  shell: logdna-agent -s "LOGDNA_APIHOST=api.{{ region }}.logging.cloud.ibm.com"
- name: set logdna-agent logging endpoint 
  shell: logdna-agent -s "LOGDNA_LOGHOST=private.logs.{{ region }}.logging.cloud.ibm.com"
- name: set logdna-agent tags
  shell: logdna-agent -t "system:{{ ansible_hostname }},region:{{ region }}"
- name: enable service at start up 
  service: 
    name: logdna-agent
    state: started

