---
  - hosts: all
    tasks:
      - name: Update package cache and packages on Debian and Ubuntu systems
        apt: upgrade=yes update_cache=yes
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Ensure basic system packages are installed on Debian and Ubuntu systems
        apt:
          pkg:
            - python3-pip
            - python3-apt
            - build-essential
            - jq
            - curl
            - wget
            - zsh
            - git
          state: present
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Update yum packages on RedHat and CentOS systems
        yum: name=* state=latest
        when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" 
      - name: Install base tools for RedHat and CentOS systems
        yum:
          name: 
            - "@Development tools"
            - nano
          state: present
        when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
