---
  - hosts: all
    vars:
      - encrypt_key: $ENCRYPT_KEY
      - datacenter: $DATACENTER
    tasks:
      - name: Update apt packages
        apt: upgrade=yes update_cache=yes
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Ensure unzip is installed
        apt:
          name: unzip
          state: present
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Add apt-key
        apt_key:
          url: https://apt.releases.hashicorp.com/gpg
          state: present
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Add consul repo 
        apt_repository:
          repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Install consul 
        apt:
          name: consul
          state: present
          update_cache: yes
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Set consul client environment variable 
        blockinfile:
          path: /root/.bashrc
          block: export CONSUL_HTTP_ADDR="http://{{ ansible_ens3.ipv4.address }}:8500"
      - name: Copy server config to /etc/consul.d/server.hcl
        copy:
          src: ./templates/server.hcl
          dest: /etc/consul.d/server.hcl
          owner: consul
          group: consul
          mode: '0640'
      - name: Template consul client file 
        template:
          src: ./templates/consul-client.j2
          dest: /etc/consul.d/consul.hcl
          owner: consul
          group: consul
          mode: '0640'
      - name: Reset consul directory permissions
        file:
          path: /etc/consul.d
          state: directory
          mode: '755'
          owner: consul
          group: consul
      - name: enable consul service and start it
        systemd:
          name: consul.service
          enabled: yes
          state: started
      - name: Reboot machine
        reboot:
