---
  - hosts: all
    vars_files:
      - vars.yaml
    tasks:
      - name: Update apt packages
        apt: upgrade=yes update_cache=yes
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Ensure unzip is installed
        apt:
          name: unzip
          state: present
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Add apt-key
        apt_key:
          url: https://apt.releases.hashicorp.com/gpg
          state: present
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Add Vault repo 
        apt_repository:
          repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Install Vault on servers 
        apt:
          name: vault
          state: present
          update_cache: yes
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Template Vault config to /etc/vault.d/vault.hcl
        template:
          src: ./templates/vault-config.j2
          dest: /etc/vault.d/vault.hcl
          owner: vault
          group: vault
          mode: '0640'
      - name: Copy over modified service file
        copy:
          src: ./templates/vault.service
          dest: /usr/lib/systemd/system/vault.service
          owner: root
          group: root
          mode: '0644'
          backup: yes
      - name: Reload systemd configs
        ansible.builtin.systemd:
          daemon_reload: yes
      - name: Reset Vault directory permissions
        file:
          path: /etc/vault.d
          state: directory
          mode: '755'
          owner: vault
          group: vault
      - name: Enable the Vault service and start it
        systemd:
          name: vault.service
          enabled: yes
          state: started
      - name: Reboot machine
        reboot:

# Create directory structure 
# /vault/data 
