---
  - hosts: all
    tasks:
      - name: Add Telegraf repo to Debian based systems
        apt_repository:
          repo: deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable
          state: present
        when: ansible_facts['os_family'] == "Debian"
      - name: Update apt packages on Debian based systems
        apt: update_cache=yes
        when: ansible_facts['os_family'] == "Debian"
      - name: Install Telegraf on Debian based systems
        apt:
          name: telegraf
          state: present
          update_cache: yes
        check_mode: no
        when: ansible_facts['os_family'] == "Debian"
      - name: Add Telegraf repo to RPM Based systems
        blockinfile:
          path: /etc/yum.repos.d/influxdb.repo
          block: |
            [influxdb]
            name = InfluxDB Repository - RHEL 
            baseurl = https://repos.influxdata.com/rhel/7/x86_64/stable/
            enabled = 1
            gpgcheck = 1
            gpgkey = https://repos.influxdata.com/influxdb.key
          create: yes 
        check_mode: no
        when: ansible_facts['os_family'] == "RedHat"
      - name: Install Telegraf on RPM based systems
        yum:
          name: telegraf
          state: present
        check_mode: no
        when: ansible_facts['os_family'] == "RedHat"
      - name: Template Telegraf configuration and send to instances
        template:
          src: ../templates/telegraf.j2
          dest: /etc/telegraf/telegraf.conf
          owner: root
          group: root
          mode: '0644'
      - name: Enable telegraf on systems  
        systemd: 
          name: telegraf
          enabled: yes
          state: started