---
  - hosts: all
    tasks:
      - name: Install Apache web server on Deb based servers 
        apt:
          name: apache2
          state: present 
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Install Apache web server on RPM based servers 
        yum:
          name: httpd
          state: present 
        when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" 
      - name: Start apache2 on Debian systems 
        systemd:
          name: apache2
          state: started 
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      - name: Start Apache web server on RPM based servers 
        systemd:
          name: httpd
          state: present 
        when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" 
